name: gonotter_app
description: GoNotter application written in Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  fluro: ^1.7.8
  dio: ^3.0.10
  rxdart: 0.24.0
  json_serializable: ^3.5.1
  json_annotation: ^3.1.1
  logger: ^0.9.4
  get_it: ^5.0.6
  retrofit: any
  flutter_secure_storage: 3.3.1
  bloc: ^6.1.0
  flutter_bloc: ^6.1.0
  equatable: ^1.2.5

dev_dependencies:
  retrofit_generator: any
  build_runner: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

